### ISSUE TITLE
TypeError: multiInput is not a function

### ISSUE THREAD

**Issue by justintemps** [alfredosalzillo/rollup-plugin-multi-input#61]
With rollup@3.3.0 I get the following error:

```
[!] TypeError: multiInput is not a function
```

Config file looks like this...

```
// rollup.config.mjs

import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import resolve from "@rollup/plugin-node-resolve";
import { createRequire } from "node:module";
import multiInput from "rollup-plugin-multi-input";
import peerDepsExternal from "rollup-plugin-peer-deps-external";
import postcss from "rollup-plugin-postcss";
import typescript from "rollup-plugin-typescript2";

const require = createRequire(import.meta.url);
const packageJson = require("./package.json");

export default {
  input: ["src/**/*.js"],
  external: [...Object.keys(packageJson.dependencies)],
  output: [
    {
      dir: "lib/cjs/",
      format: "cjs",
    },
    {
      dir: "lib/esm/",
      format: "esm",
    },
  ],
  plugins: [
    peerDepsExternal(),
    resolve({ browser: true }),
    commonjs(),
    typescript({
      useTsconfigDeclarationDir: true,
      tsconfig: "./tsconfig.build.json",
    }),
    postcss({
      extensions: [".css"],
    }),
    json(),
    multiInput(),
  ],
};

```

**Comment by mikestecker** [comment]
Having the same issue. I'm using NX with `rollup@^2.56.2`

**Comment by niorad** [comment]
As workaround, "multiInput.default()" seems to work

**Comment by justintemps** [comment]
Thanks @niorad, that does work. I don't think that's the intended behaviour though so I'll leave this open until the issue gets fixed.

**Comment by alfredosalzillo** [comment]
What version of node are you using? I think is a problem related to node resolution of commonjs modules in mjs files

**Comment by nikitaourazbaev** [comment]
@alfredosalzillo this happens for me in node v18 and node v19

**Comment by justintemps** [comment]
Thanks @alfredosalzillo, I'm using 16.4.0 in this case.

**Comment by alfredosalzillo** [comment]
@nikitaourazbaev @justintemps should be fixed in the laster release 1.3.2. Was missing the `module` specifier in the package.json

**Comment by ayan4m1** [comment]
Still an issue with 1.3.2 @alfredosalzillo , notice that your commit here is empty https://github.com/alfredosalzillo/rollup-plugin-multi-input/commit/c3fd60b919c5cc976557f28cc81b3e9c73c81b4c

`"type": "module"` is still not specified in main branch package.json - https://github.com/alfredosalzillo/rollup-plugin-multi-input/blob/main/package.json

**Comment by ryansully** [comment]
Still seeing the issue in 1.3.3. It doesn't looks like the commit in the release has any fix: https://github.com/alfredosalzillo/rollup-plugin-multi-input/commit/eb4a194878a6f3d35096eacc854770e89dd0c52a.

**Comment by benjaminrae** [comment]
I'm also still seeing the issue with 1.3.3

**Comment by willjenks** [comment]
yes, seeing the same here

**Comment by alfredosalzillo** [comment]
@nathan-kinship @willjenks @benjaminrae are you using the `mjs` extension for the rollup config file?
If case, try renaming the file extension to js

**Comment by bwhitty** [comment]
@alfredosalzillo Rollup says in their migration guide to rename to `.mjs` and this means that now we're beholden to Node.js ESM semantics.

I believe in [the Node.js ESM docs the problem is being alluded to](https://nodejs.org/api/esm.html#enabling) here:

> Inversely, authors can tell Node.js to interpret JavaScript as CommonJS via the .cjs file extension, the package.json ["type"](https://nodejs.org/api/packages.html#type) field with a value "commonjs", the [--input-type](https://nodejs.org/api/cli.html#--input-typetype) flag with a value of "commonjs", or the [--experimental-default-type](https://nodejs.org/api/cli.html#--experimental-default-typetype) flag with a value of "commonjs".

This library uses `"type": "commonjs"`: https://github.com/alfredosalzillo/rollup-plugin-multi-input/blob/main/package.json#L5

This is why you have to do `import * as multiInput from 'rollup-plugin-multi-input'` and then as described in https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/61#issuecomment-1326518652 use `multiInput.default`. 

Even though you have a `module` and `exports` field defined, you're telling Node.js to interpret this package as `commonjs`, which is causing `default` to be necessary.

**Comment by ayan4m1** [comment]
> @alfredosalzillo Rollup says in their migration guide to rename to `.mjs` and this means that now we're beholden to Node.js ESM semantics.
> 
> I believe in [the Node.js ESM docs the problem is being alluded to](https://nodejs.org/api/esm.html#enabling) here:
> 
> > Inversely, authors can tell Node.js to interpret JavaScript as CommonJS via the .cjs file extension, the package.json ["type"](https://nodejs.org/api/packages.html#type) field with a value "commonjs", the [--input-type](https://nodejs.org/api/cli.html#--input-typetype) flag with a value of "commonjs", or the [--experimental-default-type](https://nodejs.org/api/cli.html#--experimental-default-typetype) flag with a value of "commonjs".
> 
> This library uses `"type": "commonjs"`: https://github.com/alfredosalzillo/rollup-plugin-multi-input/blob/main/package.json#L5
> 
> This is why you have to do `import * as multiInput from 'rollup-plugin-multi-input'` and then as described in [#61 (comment)](https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/61#issuecomment-1326518652) use `multiInput.default`.
> 
> Even though you have a `module` and `exports` field defined, you're telling Node.js to interpret this package as `commonjs`, which is causing `default` to be necessary.

Thank you for explaining what I was trying to [last year](https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/61#issuecomment-1381229515) - not being sarcastic or negative, I genuinely mean it.

**Comment by ayan4m1** [comment]
Seeing as this issue has been incorrectly closed for over a year and the original author has minimal GH activity in the past year, I'm going to fork it and publish as `@ayan4m1/rollup-plugin-multi-input`.

**Comment by alfredosalzillo** [comment]
@ayan4m1, please open a Pull Request (PR) for your contribution. I will merge it and release it with a major release, as it could potentially cause issues with older projects.

During the troubleshooting process, I tried modifying the compiled extension, but it wasn't working with the Node.js version I was using for testing.

Please note that as of today, this plugin has become obsolete and the preserveModules option can cover all the use cases it was used for.

> ⚠️ Do you really need rollup-plugin-multi-input?
> 
> Take a look at the rollup [preserveModules](https://rollupjs.org/configuration-options/#output-preservemodules) and [preserveModulesRoot](https://rollupjs.org/configuration-options/#output-preservemodulesroot) options.

**Comment by ayan4m1** [comment]
@alfredosalzillo Just to be perfectly clear, it is extremely distasteful to me that you denied what I was saying about this issue, then went radio silent for a year after falsely claiming it was fixed, then waited for me to do the job that should have been done in 2023, and only THEN pinged me expecting me to make a second branch and duplicate my efforts so that I could make a PR against your repo. To top this all off, I had the fix for you LAST YEAR and you closed my PR saying it wasn't needed.

I will see if I have the time to do what you are asking of me in the next week or two. For now, I will just use my fork.

**Comment by alfredosalzillo** [comment]
@ayan4m1 If you felt disrespected by my behavior, I apologize. I understand that I can't and wouldn't want to force you to contribute to this project. However, I also appreciate it if we can treat each other with respect.

To ensure we're on the same page, I double-checked the thread. My last reply was on March 25th, 2023 [link to comment](https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/61#issuecomment-1483830718). The first response since then came in five days ago. Additionally, I merged your PR #67 before that, and your last interaction until this thread was two days ago.

After merging PR #67, I closed the issue and included a question in my final comment in the #67, but haven't received a response yet.

> then waited for me to do the job that should have been done in 2023

As this is an open-source project, I contribute my time voluntarily.

> To top this all off, I had the fix for you LAST YEAR and you closed my PR saying it wasn't needed.

I can't find the PR you are claiming i closed. Your other PR after the #67 is the #78 of 2 days ago. 

[List of your PRs ](https://github.com/alfredosalzillo/rollup-plugin-multi-input/pulls?q=is%3Apr+is%3Aclosed+author%3Aayan4m1).

> I will see if I have the time to do what you are asking of me in the next week or two. For now, I will just use my fork.

I understand that you may be frustrated, but I would appreciate it if we could communicate in a more constructive manner. It's important to remember that this is a free, open-source project, and contributors like myself volunteer their time and effort.

---

The project README suggests this plugin might no longer be necessary. Rollup now offers a built-in functionality that achieves the same outcome in a more streamlined way.

> ⚠️ Do you really need rollup-plugin-multi-input?
>
> Take a look at the rollup [preserveModules](https://rollupjs.org/configuration-options/#output-preservemodules) and [preserveModulesRoot](https://rollupjs.org/configuration-options/#output-preservemodulesroot) options.

**Comment by ayan4m1** [comment]
I cannot contribute to your project in a constructive way right now, I have deleted my prior post and please stop tagging me moving forward.
